{% set name = "python-utilities-jsm" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python-utilities-jsm-{{ version }}.tar.gz
  sha256: 432361767887472444ff2618e8854fd64200dc2a7053db545003571fca049e9f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - bagit
    - beautifulsoup4
    - bleach
    - cchardet
    - chardet
    - ipykernel
    - openpyxl
    - python >={{ python_min }}
    - regex
    - requests
    - six
    - w3lib

test:
  imports:
    - python_utilities
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jonathanmorgan/python_utilities
  summary: Myriad python utilities.
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonathanmorgan
